language: python
python:
  - "2.7"
# not py3 compatible yet; still uses OptionParse and some deps are borked for py3
#  - "3.3"
#  - "3.4"
before_install:
  - "pip install -U pip setuptools virtualenv python-coveralls"
install:
  - "pip install -e .[all]"
  - "git fetch --unshallow"
script:
  - "coverage run --source=bin,did -m py.test $CAPTURE tests"
after_success:
  - coveralls
  - coverage report

# Hint: To enable more detailed logging for debugging purposes,
# define the following variables in the Travis CI web interface
#
# CAPTURE=--capture=no
# DEBUG=5
