language: python
python:
  - "2.6"
  - "2.7"
# not py3 compatible yet; still uses OptionParse and some deps are borked for py3
#  - "3.3"
#  - "3.4"
before_install:
  - "pip install -U pip setuptools virtualenv coveralls"
install:
  - "python setup.py install"
script:
  - "coverage run --source=bin,did -m py.test --capture=no tests"
after_success:
  - coveralls
  - coverage report
